name: Java CI with tests

on:
  push:
    branches: [ master, work ]
  pull_request:
    branches: [ master, work ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Create containers
        run: |
          docker-compose up -d
      - name: Filling testing database
        run: |
          mvn -Dtest=FillingTestingDataBaseTest test
      - name: Run test
        run: |
          mvn test
      - name: Stop containers
        run: |
          docker-compose stop

